### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by RobertHennig** [owncloud/ocdev#26]
After following the installation instructions I call 
```
ocdev --version
```
This results in the following trace:
```
Traceback (most recent call last):
  File "/usr/bin/ocdev", line 9, in <module>
    load_entry_point('ocdev==0.0.19', 'console_scripts', 'ocdev')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/ocdev/application.py", line 20, in <module>
    from ocdev.plugins import PLUGINS
  File "/usr/lib/python2.7/site-packages/ocdev/plugins/__init__.py", line 5, in <module>
    PLUGINS = [SetUp(), StartApp(), ContinousIntegration()]
  File "/usr/lib/python2.7/site-packages/ocdev/plugins/setup/setup.py", line 30, in __init__
    super().__init__('setup')
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by Raydiation** [comment]
You've installed ocdev with pip for python 2, use the python 3 version of pip (check the readme)

**Comment by select** [comment]
@BernhardPosselt would be nice to have a link from the old dev manual https://doc.owncloud.org/server/8.0/developer_manual/app/tutorial.html to the new one stating that the instructions are outdated and do not work anymore. The hint to check the readme was also not very helpful since it did not state which readme.

**Comment by select** [comment]
Ah and of course for everybody looking to the new instructions landing here, go to https://doc.owncloud.org/server/8.1/developer_manual/app/tutorial.html and follow the development tool link.
