### ISSUE TITLE
Template not found exception

### ISSUE THREAD

**Issue by vascowhite** [owncloud/ocdev#46]
ocdev version 0.1.8 on windows 7

After setting up core with:-

    ocdev setup core --branch v8.2.2

I cd'd into the app directory and issued:-

    ocdev startapp Todo

and got the following exception message:- 

>     Traceback (most recent call last):
    File "C:\Users\relief_captain\AppData\Local\Programs\Python\Python35-32\Scripts\ocdev-script.py", line 9, in <module>
    load_entry_point('ocdev==0.1.8', 'console_scripts', 'ocdev')()
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\ocdev\application.py", line 47, in main
    plugin.run(arguments, os.getcwd(), settings)
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\ocdev\plugins\startapp\startapp.py", line 163, in r
    rendered = env.get_template(jinja_path).render(params)
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
    File "c:\users\relief_captain\appdata\local\programs\python\python35-32\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: 8.1\app\.travis.yml

The template files exist in the 8.1/app/ folder, but ocdev cannot find them for some reason.

ocdev sets up all the correct folders in the apps/todo folder, but they are all empty.

Any fixes for this?

**Comment by BernhardPosselt** [comment]
Templates for 8.2 are not yet included, see https://github.com/owncloud/ocdev/tree/master/ocdev/plugins/startapp/templates

You could simply copy the 8.1 directory to 8.2 and create a pull request

**Comment by vascowhite** [comment]
Thanks for the quick reply. The exception complains about the 8.1 templates missing, how will creating 8.2 templates help?

**Comment by BernhardPosselt** [comment]
Ah right, default owncloud version is probably 8.2

This is probably a Windows path issue, try to set it up on Linux. ownCloud is not running on Windows so basically everything related to Windows depends on contributors

**Comment by vascowhite** [comment]
Yeah, it seems to be OK on Linux.I don't want to run Owncloud on Windows, but sometimes I have to develop on windows :( it would be nice if ocdev worked on Windows too.

**Comment by BernhardPosselt** [comment]
use vagrant ssh ;)

**Comment by vascowhite** [comment]
I do :)

**Comment by BernhardPosselt** [comment]
Then this should not be an issue ;)
