### ISSUE TITLE
ocdev setup results in [Errno 2] No such file or directory: '3rdparty'

### ISSUE THREAD

**Issue by wotanii** [owncloud/ocdev#52]
I tried to set up an [owncloud-dev-environment](https://doc.owncloud.org/server/9.1/developer_manual/general/devenv.html) for the first time and I got stuck getting ocdev to do its thing: 

    bjoern@b8book:/var/www$ ocdev setup --dir /var/www/owncloud base
    Klone nach '/var/www/owncloud' ...
    remote: Counting objects: 480094, done.
    remote: Compressing objects: 100% (102/102), done.
    remote: Total 480094 (delta 31), reused 1 (delta 1), pack-reused 479991
    Empfange Objekte: 100% (480094/480094), 209.63 MiB | 7.54 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (376439/376439), Fertig.
    Prüfe Konnektivität ... Fertig.
    [Errno 2] No such file or directory: '3rdparty'
    Failed to clone repository because Git is not installed

Steps I did just before:

    sudo apt-get install apache2 mariadb-server libapache2-mod-php
    sudo apt-get install php-gd php-json php-mysql php-curl
    sudo apt-get install php-intl php-mcrypt php-imagick

    sudo apt-get install python3 python3-pip
    sudo pip3 install ocdev
    sudo chmod o+rw /var/www

This happened on gnome-ubuntu 16.04

**Comment by wotanii** [comment]
What is the 3rdparty-Directory ocdev speaks of?

>[...] because Git is not installed

could it really be related to git? How would I confirm this?

**Comment by Dagefoerde** [comment]
This happens to me as well. It can be mitigated by manually creating a `3rdparty` folder *during gut clone* in the directory that is being cloned to. 
It appears that ocdev expects a `3rdparty` folder in the repository's root, which does not exist (anymore?). The problem seems to be unrelated to git.

**Comment by wotanii** [comment]
After I did `ocdev setup --dir /var/www/owncloud base`, I also created the `3rdparty`-folder in another terminal. 

Now  the first step runs fine, but it fails later anyways. Eventually it says

    Submodul 'documentation/wiki' (git://github.com/owncloud/gallery.wiki) für Pfad 'documentation/wiki' in die Konfiguration eingetragen.
    Klone nach 'documentation/wiki' ...
    fatal: unable to connect to github.com:

and indeed: when I do `git clone git://github.com/owncloud/gallery.wiki` it gives me the same answer. When I do `git clone 'git@github.com:owncloud/core.git` manually, it works though.

here is the ocdev's entire output:

    bjoern@b8book:/var/www$ ocdev setup --dir /var/www/owncloud base
    Klone nach '/var/www/owncloud' ...
    remote: Counting objects: 480729, done.
    remote: Compressing objects: 100% (182/182), done.
    remote: Total 480729 (delta 39), reused 0 (delta 0), pack-reused 480546
    Empfange Objekte: 100% (480729/480729), 209.99 MiB | 4.35 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (376830/376830), Fertig.
    Prüfe Konnektivität ... Fertig.
    Bereits auf 'master'
    Ihr Branch ist auf dem selben Stand wie 'origin/master'.
    Klone nach 'news' ...
    remote: Counting objects: 60405, done.
    remote: Total 60405 (delta 0), reused 0 (delta 0), pack-reused 60405
    Empfange Objekte: 100% (60405/60405), 37.23 MiB | 7.13 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (33927/33927), Fertig.
    Prüfe Konnektivität ... Fertig.
    Klone nach 'activity' ...
    remote: Counting objects: 10621, done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 10621 (delta 0), reused 0 (delta 0), pack-reused 10617
    Empfange Objekte: 100% (10621/10621), 2.83 MiB | 2.66 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (7860/7860), Fertig.
    Prüfe Konnektivität ... Fertig.
    Klone nach 'gallery' ...
    remote: Counting objects: 18718, done.
    remote: Compressing objects: 100% (9/9), done.
    remote: Total 18718 (delta 1), reused 0 (delta 0), pack-reused 18709
    Empfange Objekte: 100% (18718/18718), 8.03 MiB | 1.55 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (12199/12199), Fertig.
    Prüfe Konnektivität ... Fertig.
    Submodul 'documentation/wiki' (git://github.com/owncloud/gallery.wiki) für Pfad 'documentation/wiki' in die Konfiguration eingetragen.
    Klone nach 'documentation/wiki' ...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.112]: errno=Das Netzwerk ist nicht erreichbar

    fatal: Klonen von 'git://github.com/owncloud/gallery.wiki' in Submodul-Pfad 'documentation/wiki' fehlgeschlagen
    fatal: Zielpfad 'gallery' existiert bereits und ist kein leeres Verzeichnis.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 149, in clone_fallback
        return self.clone_repo(url, branch, directory, no_history)
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 171, in clone_repo
        return check_call(cmd)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', '--recursive', '-b', 'master', 'https://github.com/owncloud/gallery.git']' returned non-zero exit status 128

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/ocdev", line 9, in <module>
        load_entry_point('ocdev==0.2.2', 'console_scripts', 'ocdev')()
      File "/usr/local/lib/python3.5/dist-packages/ocdev/application.py", line 47, in main
        plugin.run(arguments, os.getcwd(), settings)
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 57, in run
        self.setup(arguments, directory, settings)
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 124, in setup
        self.clone_fallback(app_url, branch, None, no_history)
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 151, in clone_fallback
        return self.clone_repo(url, 'master', directory, no_history)
      File "/usr/local/lib/python3.5/dist-packages/ocdev/plugins/setup/setup.py", line 171, in clone_repo
        return check_call(cmd)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', '--recursive', '-b', 'master', 'https://github.com/owncloud/gallery.git']' returned non-zero exit status 128
    bjoern@b8book:/var/www$

**Comment by wotanii** [comment]
Note: When I install just core instead of base, it seems to work. So I suspect the problem is with the forking of the gallery-plugin. 

output: 

    bjoern@b8book:/var/www$ ocdev setup --dir /var/www/owncloud core
    Klone nach '/var/www/owncloud' ...
    remote: Counting objects: 480729, done.
    remote: Compressing objects: 100% (182/182), done.
    remote: Total 480729 (delta 39), reused 0 (delta 0), pack-reused 480546
    Empfange Objekte: 100% (480729/480729), 209.99 MiB | 8.10 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (376830/376830), Fertig.
    Prüfe Konnektivität ... Fertig.
    Bereits auf 'master'
    Ihr Branch ist auf dem selben Stand wie 'origin/master'.

    Successfully set up development environment!

    Setup ownCloud by changing into the cloned directory and run

        ocdev server

    and setup your installation at http://localhost:8080

**Comment by wotanii** [comment]
After just installing core, I ran make, but it was missing "sabre/dav". I fixed it by `sudo apt-get install php-sabre-dav`. It seems, that some dependency of the php-sabre-dav packaged fixed, what was actually missing.  


Then I ran make and it worked. When starting the server, it complained about a missing `php-zip`. After `apt-get install php-zip` the server started successfully.
